<?php
$select_query = " SELECT
 DOCINFO.DI_REF,
 DOCINFO.DI_DATE,
 DOCINFO.DI_CRE_BY,
 DOCTYPE.DT_DOCCODE,
 DOCTYPE.DT_THAIDESC,
 DEPTTAB.DEPT_CODE,
 DEPTTAB.DEPT_THAIDESC,
 DEPTTAB.DEPT_ENGDESC,
 TRANSTKH.TRH_N_QTY,
 TRANSTKH.TRH_N_ITEMS,
 TRANSTKD.TRD_SEQ,
 TRANSTKD.TRD_KEYIN,
 TRANSTKD.TRD_SH_CODE,
 TRANSTKD.TRD_SH_NAME,
 TRANSTKD.TRD_UTQNAME,
 TRANSTKD.TRD_SH_QTY,
 TRANSTKD.TRD_SH_UPRC,
 TRANSTKD.TRD_SH_GSELL,
 TRANSTKD.TRD_SH_GAMT,
 TRANSTKD.TRD_G_KEYIN,
 WARELOCATION1.WL_CODE,
 WARELOCATION1.WL_NAME,
 WARELOCATION2.WL_CODE AS WL_CODE_TO,
 WARELOCATION2.WL_NAME AS WL_NAME_TO,
 DOCINFO.DI_CRE_DATE,
 DOCINFO.DI_REMARK
FROM
 DOCINFO,
 DOCTYPE,
 TRANSTKH,
 TRANSTKD,
 DEPTTAB,
 PRJTAB,
 BRANCH, 
 MKTPLAN,
 PRMTPLAN,
 WARELOCATION WARELOCATION1,
 WARELOCATION WARELOCATION2,
 WAREHOUSE,
 SKUMASTER,
 GOODSMASTER,
 ICCAT,
 ICDEPT,
 BRAND,
 SKUALT,
 ICCOLOR,
 ICSIZE " ;

$sql_cond = " WHERE
 (DOCINFO.DI_DT = DOCTYPE.DT_KEY) AND
 (DOCINFO.DI_KEY = TRANSTKH.TRH_DI) AND
 (TRANSTKH.TRH_KEY = TRANSTKD.TRD_TRH) AND
 (TRANSTKH.TRH_DEPT = DEPTTAB.DEPT_KEY) AND
 (TRANSTKH.TRH_PRJ = PRJTAB.PRJ_KEY) AND
 (TRANSTKH.TRH_BR=BRANCH.BR_KEY)  AND 
 TRANSTKH.TRH_MKTP=MKTPLAN.MKTP_KEY AND 
 TRANSTKH.TRH_PRMT=PRMTPLAN.PRMT_KEY AND
 (TRANSTKD.TRD_WL = WARELOCATION1.WL_KEY) AND  (DOCTYPE.DT_PROPERTIES=311) AND
 (WARELOCATION1.WL_WH = WAREHOUSE.WH_KEY) AND
 (TRANSTKD.TRD_TO_WL = WARELOCATION2.WL_KEY) AND
 (TRANSTKD.TRD_SKU = SKUMASTER.SKU_KEY) AND
 (TRANSTKD.TRD_GOODS = GOODSMASTER.GOODS_KEY) AND
 (SKUMASTER.SKU_ICCAT = ICCAT.ICCAT_KEY) AND
 (SKUMASTER.SKU_ICDEPT = ICDEPT.ICDEPT_KEY) AND
 (SKUMASTER.SKU_BRN = BRAND.BRN_KEY) AND
 (SKUMASTER.SKU_SKUALT = SKUALT.SKUALT_KEY) AND
 (SKUMASTER.SKU_ICCOLOR = ICCOLOR.ICCOLOR_KEY) AND
 (SKUMASTER.SKU_ICSIZE = ICSIZE.ICSIZE_KEY) AND
 (DOCINFO.DI_ACTIVE = 0) " ;

$sql_order = " ORDER BY DOCINFO.DI_REF ASC, DOCINFO.DI_DATE ASC, TRANSTKD.TRD_SEQ ASC ";